chains:
  - name: osmosis-1
    type: osmosis
    image: ghcr.io/cosmology-tech/starship/osmosis:v19.2.0
    numValidators: 1
    ports:
      rest: 1313
      rpc: 26653
    resources:
      cpu: "0.5"
      memory: "500M"
    genesis:
      app_state:
        gov:
          voting_params:
            voting_period: 90s
        staking:
          params:
            unbonding_time: 9000s

  - name: cosmoshub-4
    type: cosmos
    image: ghcr.io/cosmology-tech/starship/gaia:v13.0.0
    numValidators: 1
    ports:
      rest: 1317
      rpc: 26657
    resources:
      cpu: "0.5"
      memory: "500M"
    genesis:
      app_state:
        gov:
          voting_params:
            voting_period: 9000s
        staking:
          params:
            unbonding_time: 9000s

relayers:
  - name: osmos-cosmos
    type: hermes
    replicas: 1
    chains:
      - osmosis-1
      - cosmoshub-4
    resources:
      cpu: "0.5"
      memory: "500M"
    config:
      chains:
        - id: osmosis-1
          trusting_period: 8000s
        - id: cosmoshub-4
          trusting_period: 8000s

registry:
  enabled: true
  ports:
    rest: 8081
  resources:
    cpu: "0.1"
    memory: "100M"

exposer:
  resources:
    cpu: "0.1"
    memory: "100M"

explorer:
  enabled: true
  ports:
    rest: 8080
