chains:
  - name: injective-999
    type: injective
    image: ghcr.io/cosmology-tech/starship/injective:v1.11.6
    numValidators: 1
    ports:
      rest: 1317
      rpc: 26657
      faucet: 8007

  - name: cosmos-2
    type: cosmos
    numValidators: 1
    ports:
      rest: 1313
      rpc: 26653
      faucet: 8003

relayers:
  - name: injective-cosmos
    type: hermes
    replicas: 1
    chains:
      - injective-999
      - cosmos-2

explorer:
  enabled: true
  ports:
    rest: 8080

registry:
  enabled: true
  ports:
    rest: 8081
    grpc: 9091
